name: netwin_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1
  http: ^0.13.6
  connectivity_plus: ^5.0.1
  modal_progress_hud_nsn: ^0.4.0
  webview_flutter: ^4.4.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.1
  google_maps_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
